---
title: CloudNation
url: https://cloudnation.blog
logo: "/assets/images/CloudNation_Logo_Grey.png"
masthead_title: " "
# subtitle: "Cloud, Networking, Linux.."
title_separator: "|"
email: info@cloudnation.blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to CloudNation, your one-stop destination for expert insights, practical tips, and the latest news on cloud computing, networking, Linux, AWS, security, and other cutting-edge tech topics.
  Our blog features a team of seasoned tech enthusiasts who share their knowledge, experience, and insights to help you stay informed and up-to-date in the fast-paced world of technology.
  From deep dives into the latest trends and emerging technologies to practical how-to guides and industry news, CloudNation has everything you need to stay on top of your game.
  Join us today and discover a wealth of valuable resources for all your tech needs.
twitter_username: cloudnationblog
github_username: cloudnationblog
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# author:
#   name   : "First Lastname"
#   avatar : "/assets/images/bio-photo.jpg"
#   bio    : "My awesome biography constrained to a sentence or two goes here."
#   links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/cloudnation.blog"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cloudnationblog"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cloudnationblog/"
    - label: "Privacy Policy & Terms"
      icon: "fas fa-fw fa-lock"
      url: /policy-terms/
    # - label: ""
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      classes: wide
      toc: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Custom Config
minimal_mistakes_skin: dark
repository: cloudnationblog/blog
timezone: America/New_York
atom_feed:
  hide: true
breadcrumbs: true  # disabled by default
head_scripts:
  - /assets/js/lightbox.js
social:
  type: Organization
  links:
    - "https://twitter.com/cloudnationblog"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-NT5HD0NQ28"
